eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8761/eureka/}


server:
    port: 8081 # Facebook and GitHub is configured for this port localhost:8081

---
spring:
    profiles: default
security:
    oauth2:
        client:
            clientId: 1492505737746691
            clientSecret: 0132724a13c0d6235c426ca5c9a592e3
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://graph.facebook.com/me

---
spring:
    profiles: github
security:
    oauth2:
        client:
            clientId: 333f62c05ad5ddb9002a
            clientSecret: 7ab5e8a8a9bc5478d403481f9f11849e1e7f6208
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://api.github.com/user
            preferTokenInfo: false