server:
  port: 8180

spring:
    application:
        name: catalogg

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/